{- 
  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
-}

module Main where

import Data.Maybe
main :: IO ()
main = print (minimum $ [x|x<-(take 15000 $ genGTN),(length $ factors x) > 500])



-- Generate Triangle Number Series
--gtn :: (Enum a, Num a) => a -> [a]
genGTN = gtn 1

gtn x = sum [1..x]:gtn(x+1)


factors n = let candidates = [2..floor (sqrt (fromInteger n))] 
            in (1,n) : (catMaybes $ map (\x -> if n `mod` x == 0 then Just (x, n `div` x) else Nothing) candidates) >>= \(x,y) -> [x,y]


